# Generated by Django 3.2.8 on 2022-06-11 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=50, verbose_name='first name')),
                ('lastName', models.CharField(max_length=50, verbose_name='last name')),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wishlist.user', verbose_name='wishlist owner')),
            ],
        ),
        migrations.CreateModel(
            name='WishlistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(max_length=200, verbose_name='item name')),
                ('linkToItem', models.TextField(blank=True, verbose_name='link to item')),
                ('itemIsClaimed', models.BooleanField(verbose_name='item has been claimed')),
                ('wishlistId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wishlist.wishlist', verbose_name='wishlist id')),
            ],
        ),
    ]
