# Generated by Django 3.2.8 on 2022-06-11 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlistentry',
            name='itemIsClaimed',
            field=models.BooleanField(default=False, verbose_name='item has been claimed'),
        ),
    ]
