# Generated by Django 3.2.8 on 2022-06-12 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0003_wishlist_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='name',
            field=models.CharField(default='New Wishlist', max_length=50),
        ),
    ]
